import React from 'react';

const PrescriptionPreview = ({ prescription, patient, doctor, date }) => {
  if (!prescription) return null;

  const { medicines, notes } = prescription;

  return (
    <div
      id="prescription-preview"
      className="bg-white rounded-xl border-2 border-gray-200 p-6 sm:p-8"
    >
      {/* Header */}
      <div className="text-center border-b-2 border-blue-600 pb-4 mb-4">
        <h1 className="text-xl sm:text-2xl font-bold text-blue-700">
          🏥 CLINIC MANAGEMENT
        </h1>
        <p className="text-gray-500 text-sm mt-1">Digital Prescription</p>
      </div>

      {/* Doctor & Patient Info */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6 text-sm">
        <div>
          <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">
            Doctor
          </p>
          <p className="font-semibold text-gray-900">Dr. {doctor?.name}</p>
          <p className="text-gray-500">{doctor?.specialization}</p>
        </div>
        <div className="sm:text-right">
          <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">
            Patient
          </p>
          <p className="font-semibold text-gray-900">{patient?.name}</p>
          <p className="text-gray-500">
            Age: {patient?.age} • Phone: {patient?.phone}
          </p>
          <p className="text-gray-400 text-xs mt-1">
            Date: {date}
          </p>
        </div>
      </div>

      {/* Medicines Table */}
      <div className="mb-4">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
          Prescribed Medicines
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-blue-600 text-white">
                <th className="text-left px-3 py-2 rounded-tl-lg">Medicine</th>
                <th className="text-left px-3 py-2">Dosage</th>
                <th className="text-left px-3 py-2">Frequency</th>
                <th className="text-left px-3 py-2">Duration</th>
                <th className="text-left px-3 py-2 rounded-tr-lg">Instructions</th>
              </tr>
            </thead>
            <tbody>
              {medicines?.map((med, idx) => (
                <tr
                  key={idx}
                  className={idx % 2 === 0 ? 'bg-gray-50' : 'bg-white'}
                >
                  <td className="px-3 py-2 font-medium text-gray-900 border-b border-gray-100">
                    {med.name}
                  </td>
                  <td className="px-3 py-2 text-gray-600 border-b border-gray-100">
                    {med.dosage}
                  </td>
                  <td className="px-3 py-2 text-gray-600 border-b border-gray-100">
                    {med.frequency}
                  </td>
                  <td className="px-3 py-2 text-gray-600 border-b border-gray-100">
                    {med.duration} day{med.duration > 1 ? 's' : ''}
                  </td>
                  <td className="px-3 py-2 text-gray-600 border-b border-gray-100">
                    {med.instructions || '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Notes */}
      {notes && (
        <div className="mb-4 bg-yellow-50 border border-yellow-200 rounded-lg p-3">
          <p className="text-xs font-semibold text-yellow-700 uppercase tracking-wide mb-1">
            Additional Notes
          </p>
          <p className="text-sm text-gray-700">{notes}</p>
        </div>
      )}

      {/* Footer */}
      <div className="border-t border-gray-200 pt-4 mt-6 text-center">
        <p className="text-xs text-gray-400">
          This is a digitally generated prescription
        </p>
        <p className="text-xs text-gray-400 mt-1">
          Generated by Clinic Management App
        </p>
      </div>
    </div>
  );
};

export default PrescriptionPreview;